version: '3.7'

services:
  postgres-server:
    container_name: postgres-server-bcs-demo
    image: postgres:12.1-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bcs
    ports:
      - 5432:5432

volumes:
    db-data:
